# Generated by Django 2.2 on 2019-04-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logging_time', models.DateTimeField(auto_now_add=True, verbose_name='Logging time')),
                ('logging_type', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], db_index=True, max_length=6, verbose_name='Logging type')),
                ('logging_text', models.TextField(verbose_name='Logging text')),
            ],
            options={
                'verbose_name': 'Log line',
                'verbose_name_plural': 'Log lines',
                'ordering': ['-logging_time'],
            },
        ),
    ]
