# Generated by Django 2.2 on 2019-04-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_edit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last change time'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_editor_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last editor IP'),
        ),
    ]
